##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

## Persist workspace 1
workspace = 1, persistent:true

## Open Discord on special Discord Workspace
windowrule = match:class ^(vesktop)$, workspace special:discord
windowrule = match:workspace special:discord, border_color rgba($th_secondary) rgba($th_secondary-s) 45deg

## Spotify special workspace (for usage with scripts/spotify.sh)
windowrule = match:class (spotify)$, workspace special:spotify
windowrule = match:workspace special:spotify, border_color rgba($th_secondary) rgba($th_secondary-s) 45deg

## Open applications in specific workspaces
windowrule = match:class ^(steam)$, workspace 10
windowrule = match:class ^(pcsx2-qt)$, workspace 11
windowrule = match:class ^(steam_app_.*)$, workspace 11 silent

## VRR
windowrule = match:class ^(steam_app_.*)$, content game
windowrule = match:workspace 10, content game
windowrule = match:workspace 11, content game

## Thunar
windowrule = match:initial_class ^thunar$, match:title ^File Operation Progress$, float true, center true, size 600 100

## Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize


