require("hyprland.monitors")
require("hyprland.env")
require("hyprland.inputs")
require("hyprland.binds")
require("hyprland.styles")
require("hyprland.window_rules")

hl.on("hyprland.start", function ()
    hl.exec_cmd("waybar & hyprpaper & swaync")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("sway-audio-idle-inhibit")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("sleep 3 && pw-play ~/.dotfiles/themes/archlukka/sounds/startup.wav")
end)
