general {
  hide_cursor = true
}

background {
  monitor = # monitor-agnostic
  path = ~/.dotfiles/themes/basic/wallpapers/0-6-0.jpg
  blur_passes = 1
  blur_size = 7
}

label {
  monitor =
  text = $TIME
  font_size = 100
  valign = top
  position = 0, -15%
}

input-field {
  monitor =
  size = 10%, 5%
  font_family = Noto Sans
  dots_size = 0.15
}